import { asset } from "@/lib/content";

type Props = {
  src: string;
  alt: string;
  width: number;
  height: number;
  /** Variant widths generated by scripts/prepare-responsive-images.mjs (`name-{w}.webp`). */
  widths?: number[];
  /** `sizes` attribute describing the rendered width; required when `widths` is set. */
  sizes?: string;
  /** Above-the-fold image: eager load with high fetch priority. */
  priority?: boolean;
  className?: string;
};

/**
 * Plain <img> with a srcset built from pre-generated variants. Works with
 * `output: "export"` (no image optimizer) and keeps width/height for CLS.
 */
export function Picture({
  src,
  alt,
  width,
  height,
  widths,
  sizes,
  priority,
  className,
}: Props) {
  const srcSet = widths
    ? [
        ...widths.map(
          (w) => `${asset(src.replace(/\.webp$/, `-${w}.webp`))} ${w}w`,
        ),
        `${asset(src)} ${width}w`,
      ].join(", ")
    : undefined;
  return (
    <img
      src={asset(src)}
      srcSet={srcSet}
      sizes={srcSet ? sizes : undefined}
      alt={alt}
      width={width}
      height={height}
      className={className}
      decoding="async"
      loading={priority ? undefined : "lazy"}
      fetchPriority={priority ? "high" : undefined}
    />
  );
}
